version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: oneway-app
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  traefik:
    external: true 